<Project>
	<PropertyGroup Label="Nuget">
		<Authors>Clancini</Authors>
		<Product>Dialuverc</Product>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl></PackageProjectUrl>
		<RepositoryUrl></RepositoryUrl>
	</PropertyGroup>

	<ItemGroup>
    	<AdditionalFiles Include="$(MSBuildThisFileDirectory)/CodeAnalysis/BannedSymbols.txt" />
		<GlobalAnalyzerConfigFiles Include="$(MSBuildThisFileDirectory)/CodeAnalysis/.globalconfig" />
  	</ItemGroup>
</Project>